language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install Django>=3.1
  - pip install requests
# command to run tests
script:
  - python hello/manage.py makemigrations
  - python hello/manage.py migrate
  - python hello/manage.py test firstapp
