language: python
python:
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r Django>=3.1
# command to run tests
script:
  - python manage.py test
