# Generated by Django 3.1 on 2020-10-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=65)),
                ('listeners', models.IntegerField()),
                ('scrobbles', models.IntegerField()),
                ('ratio', models.FloatField()),
                ('last_seen', models.DateField()),
            ],
        ),
    ]
